Rework the action runner
platisd/clang-tidy-pr-comments pull request #48
Opened 2023-11-03 23:14 UTC by oleg-derevenetz

fix #46
fix #47

This PR offers an almost completely rewritten runner script based on new principles. Here is an example of its work:

https://github.com/oleg-derevenetz/fheroes2/pull/160
https://github.com/oleg-derevenetz/fheroes2/actions/runs/6750999770/job/18354374497#step:8:15

Highlights:

* Completely new logic for working with suggestions. Multiple changes in one row, in adjacent rows or in different files are no longer a problem.
* Improved logging.
* Modernized code (with the assistance of `pylint`).

2023-11-04 09:37 UTC, platisd commented
Wow you're a hero! :rocket: :heart: 
Taking a look.

2023-11-04 10:39 UTC, platisd requested changes
I went through it and it looks very good. Your test run also looks like there are no obvious regressions. :100: 
Should probably have something like this as test cases. :tired_face: 

However, it's a bit hard to follow what has stayed the same, since things have moved around.

For clarity and to make sure we haven't missed anything, can you please point out the function(s) that have the bulk of changes in the parsing logic?
Is it primarily `generate_review_comments`?

2023-11-04 10:39 UTC, platisd commented on run_action.py
> +                        assert False
```suggestion
                        assert False, "Please report this to the repository maintainer"
```

2023-11-04 12:39 UTC, oleg-derevenetz commented
> However, it's a bit hard to follow what has stayed the same, since things have moved around.

Not much really :)

> For clarity and to make sure we haven't missed anything, can you please point out the function(s) that have the bulk of changes in the parsing logic?
Is it primarily `generate_review_comments`?

In fact, yes. But the logic of processing replacements has been radically changed. Now, for each diagnostics with suggestions, all the suggestions from that diagnostics belonging to a particular file are applied to that file and then `difflib` is used to compute the line-by-line diff (similar to unified diff), which is then processed to generate the suggestion diffs suitable for GitHub. This allows generation of just one suggestion for cases of multiple changes in one line or in adjacent lines, and in general, it makes logic easier and simpler.

2023-11-06 15:46 UTC, platisd approved these changes

2023-11-06 15:46 UTC, merged

2023-11-06 15:47 UTC, platisd commented
Great job! :handshake: :rocket: :heart: 
I'll bump the release after no one complains for a week or so :grin: